version: '3'

services:
  web:
    build: .
    command: gunicorn sns_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  cron:
    build: .
    command: python manage.py run_scheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
